### ISSUE TITLE
.env error

### ISSUE THREAD

**Issue by Shentia** [ffurqanuddin/lofiii#45]
I got this error when try to run the project on iPhone 16
No file or variants found for asset: .env.

I created the .env in root then I got this error 

Launching lib/main.dart on iPhone 16 Plus in debug mode...
Xcode build done.                                           29.0s
Connecting to VM Service at ws://127.0.0.1:59517/LQBukPrCBSE=/ws
Connected to the VM Service.
[log] Connectivity registered
[log] AudioPlayer registered
[log] VolumeController registered
[log] Dio registered
[log] ImagePicker registered
[log] FlipCardController registered
[log] OnAudioQuery registered
[log] ScrollController registered
[log] YouTubeDataRepository registered
[log] Floating registered
[log] Locator initialized
[log] Initializing Hive

**Comment by frkudn** [comment]
I apologize for the inconvenience. This project is not fully compatible with iOS and is currently deprecated, as alternative solutions with advanced features are coming soon. Lofiii 2.0 will be released shortly.
